#!/bin/bash
pythonpath='/usr/local/devops/devops'
pidfile='/var/run/uwsgi'
logpath='/data/devops/log'
lockdir='/var/lock/subsys'
lock_file_path=$lockdir/uwsgi

mkdir -pv $pidfile


function start(){
#    echo "start uwsgi web and api.........."
    if [ -e $lock_file_path ];then
        echo -e "\033[31mUWSGI IS ALREADY START.......\033[0m"
        exit
    fi
    cd $pythonpath
    source $pythonpath/../.venv/bin/activate
    if [ $? -eq 0 ]
    then
        uwsgi --ini config_web.ini -d $logpath/web/uwsgi_web.log  --pidfile $pidfile/web.pid &&
        uwsgi --ini config_api.ini -d $logpath/api/uwsgi_api.log   --pidfile $pidfile/api.pid ; return_value=$?
        if test -w "$lockdir"
        then
            touch $lock_file_path
            echo -e "\033[34mSTART SUCCESS!!!\033[0m"
        fi
        exit $return_value
    else
        echo "start uwsgi web and api failed.......permission deny!"
    fi
    
}

function stop(){
#    echo "STOP UWSGI web and api........"
    killall uwsgi  >/dev/null 2>&1
    if [ $? -eq 0 ];then
        rm -rf $lock_file_path
        echo -e "\033[34mSTOP UWSGI WEB ADN API SUCCESS!!!\033[0m"
    elif [ $? -eq 1 ];then
        echo -e "\033[34mUWSGI IS NOT RUNNING\033[0m"
    fi
}


function status(){
    if [ ! -e $lock_file_path ]
    then
        echo "UWSGI IS NOT RUNNING....."
        exit 
    else
        ps -ef | grep uwsgi | grep -v "grep"
    fi
}




case "$1" in
    start)
    start
    ;;
    stop)
    stop
    ;;
    status)
    status
    ;;
*)
    echo $"Usage: $0 {start|stop|relstart|status}"
    exit 2
esac
